
services:

  userservice-2-app:
    restart: unless-stopped
    build:
      context: user-service-2
      dockerfile: ./src/main/docker/Dockerfile
    image: ${DOCKER_REG}/userservice2:${TAG}
    ports:
      - "9000:9000"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m

      # bridge so dynamic logging level can be passed in via docker compose (environment variable passed in my be declared in this file)
      - LOGGING_LEVEL_ORG_ORCID_MP=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT_RESTCLIENT=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP_CLIENT=${APP_LOG_LEVEL:-INFO}
      - SPRING_DATA_MONGODB_URI=${MONGO_DB}
      - SPRING_DATA_MONGODB_DATABASE=userservice
      - APPLICATION_MAIL_DOMAIN=${MAIL_DOMAIN}
      - APPLICATION_MAIL_API_KEY=${MAIL_API_KEY}
      - APPLICATION_MAIL_API_URL=${MAIL_API_URL}
      - APPLICATION_MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APPLICATION_BASE_URL=${BASE_URL}
      - APPLICATION_MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - APPLICATION_MAIL_TEST_MODE=${MAIL_TEST_MODE}
      - APPLICATION_ENCRYPT_SALT=${USER_ENCRYPT_SALT}
      - APPLICATION_ENCRYPT_KEY=${USER_ENCRYPT_KEY}
      - APPLICATION_INTERNAL_CLIENT_ID=user-service-internal
      - APPLICATION_INTERNAL_CLIENT_SECRET=${USER_SERVICE_INTERNAL_CLIENT_SECRET}
      - APPLICATION_USER_SERVICE_URL=${USER_SERVICE_URL}
      - APPLICATION_SECURITY_JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - APPLICATION_SECURITY_JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - APPLICATION_SECURITY_JWT_KEY_ID=${JWT_KEY_ID}
      - APPLICATION_HTTPCLIENT_MAX_CONN_TOTAL=${HTTP_MAX_CONN_TOTAL}
      - APPLICATION_HTTPCLIENT_MAX_CONN_PER_ROUTE=${HTTP_MAX_CONN_PER_ROUTE}
      - APPLICATION_HTTPCLIENT_CONNECTION_TIME_TO_LIVE=${HTTP_CONN_TTL}
      - APPLICATION_MEMBER_SERVICE_URL=${MEMBER_SERVICE_URL}
      - APPLICATION_RELEASE_VERSION=${TAG}
      - APPLICATION_UI_BASE_URL=${UI_BASE_URL}
      - APPLICATION_INTERNAL_ASSERTION_SERVICE_ID=assertion-service-internal
      - APPLICATION_INTERNAL_ASSERTION_SERVICE_CLIENT_SECRET=${ASSERTION_SERVICE_INTERNAL_CLIENT_SECRET}
      - APPLICATION_SECURITY_ISSUER_URL=${ISSUER_URL}
      - UI_REDIRECT_URI=${UI_BASE_URL}/en/auth/callback
      - UI_POST_LOGOUT_REDIRECT_URI=${UI_BASE_URL}/en/login
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
      - ${HOST_KEYSTORE_DIR:-./keystores}:/keystores

  assertionservice-2-app:
    restart: unless-stopped
    build:
      context: assertion-service-2
      dockerfile: ./src/main/docker/Dockerfile
    image: ${DOCKER_REG}/assertionservice2:${TAG}
    ports:
      - "9020:9020"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m

      # bridge so dynamic logging level can be passed in via docker compose (environment variable passed in my be declared in this file)
      - LOGGING_LEVEL_ORG_ORCID_MP=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT_RESTCLIENT=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP_CLIENT=${APP_LOG_LEVEL:-INFO}
      - SPRING_DATA_MONGODB_URI=${MONGO_DB}
      - SPRING_DATA_MONGODB_DATABASE=assertionservice
      - APPLICATION_USER_SERVICE_URL=${USER_SERVICE_URL}
      - APPLICATION_INTERNAL_ASSERTION_SERVICE_ID=assertion-service-internal
      - APPLICATION_INTERNAL_ASSERTION_SERVICE_CLIENT_SECRET=${ASSERTION_SERVICE_INTERNAL_CLIENT_SECRET}
      - APPLICATION_LANDING_PAGE_URL=${LANDING_PAGE_URL}
      - APPLICATION_MEMBER_SERVICE_URL=${MEMBER_SERVICE_URL}
      - APPLICATION_HTTPCLIENT_MAX_CONN_TOTAL=${HTTP_MAX_CONN_TOTAL}
      - APPLICATION_HTTPCLIENT_MAX_CONN_PER_ROUTE=${HTTP_MAX_CONN_PER_ROUTE}
      - APPLICATION_HTTPCLIENT_CONNECTION_TIME_TO_LIVE=${HTTP_CONN_TTL}
      - APPLICATION_MAIL_API_KEY=${MAIL_API_KEY}
      - APPLICATION_MAIL_API_URL=${MAIL_API_URL}
      - APPLICATION_MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APPLICATION_MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - APPLICATION_MAIL_TEST_MODE=false
      - APPLICATION_MAIL_MEMBER_ASSERTION_STATS_RECIPIENT=${MEMBER_ASSERTION_STATS_RECIPIENT}
      - APPLICATION_ORCIDAPIENDPOINT=${ORCID_API_ENDPOINT}
      - APPLICATION_JWT_SIGNATURE_URL=${JWT_SIGNATURE_URL}
      - APPLICATION_INTERNAL_API_ENDPOINT=${INTERNAL_API_ENDPOINT}
      - APPLICATION_TOKEN_EXCHANGE_ENDPOINT=${TOKEN_EXCHANGE_ENDPOINT}
      - APPLICATION_TOKEN_EXCHANGE_CLIENT_ID=${TOKEN_EXCHANGE_CLIENT_ID}
      - APPLICATION_TOKEN_EXCHANGE_CLIENT_SECRET=${TOKEN_EXCHANGE_CLIENT_SECRET}
      - APPLICATION_TOKEN_EXCHANGE_GRANT_TYPE=${TOKEN_EXCHANGE_GRANT_TYPE}
      - APPLICATION_TOKEN_EXCHANGE_SUBJECT_TOKEN_TYPE=${TOKEN_EXCHANGE_SUBJECT_TOKEN_TYPE}
      - APPLICATION_TOKEN_EXCHANGE_REQUESTED_TOKEN_TYPE=${TOKEN_EXCHANGE_REQUESTED_TOKEN_TYPE}
      - STORED_FILE_LIFESPAN=${STORED_FILE_LIFESPAN}
      - APPLICATION_RESEND_NOTIFICATION_DAYS=${RESEND_NOTIFICATION_DAYS}
      - APPLICATION_RESEND_NOTIFICATION_CRON=${RESEND_NOTIFICATION_CRON}
      - MEMBER_ASSERTION_STATS_CRON=${CRON_GENERATE_MEMBER_ASSERTION_STATS}
      - APPLICATION_SYNC_AFFILIATIONS_DELAY=${CRON_SYNC_AFFILIATIONS}
      - APPLICATION_ENCRYPT_SALT=${ASSERTION_ENCRYPT_SALT}
      - APPLICATION_ENCRYPT_KEY=${ASSERTION_ENCRYPT_KEY}
      - APPLICATION_SECURITY_ISSUER_URL=${ISSUER_URL}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
      - ${MEMBER_ASSERTION_STATS_VOLUME:-/files}:/files

  memberservice-2-app:
    restart: unless-stopped
    build:
      context: member-service-2
      dockerfile: ./src/main/docker/Dockerfile
    image: ${DOCKER_REG}/memberservice2:${TAG}
    ports:
      - "9010:9010"
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m

      # bridge so dynamic logging level can be passed in via docker compose (environment variable passed in my be declared in this file)
      - LOGGING_LEVEL_ORG_ORCID_MP=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_CLIENT_RESTCLIENT=${APP_LOG_LEVEL:-INFO}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP_CLIENT=${APP_LOG_LEVEL:-INFO}
      - SPRING_DATA_MONGODB_URI=${MONGO_DB}
      - SPRING_DATA_MONGODB_DATABASE=memberservice
      - APPLICATION_HTTPCLIENT_MAX_CONN_TOTAL=${HTTP_MAX_CONN_TOTAL}
      - APPLICATION_HTTPCLIENT_MAX_CONN_PER_ROUTE=${HTTP_MAX_CONN_PER_ROUTE}
      - APPLICATION_HTTPCLIENT_CONNECTION_TIME_TO_LIVE=${HTTP_CONN_TTL}
      - APPLICATION_USER_SERVICE_URL=${USER_SERVICE_URL}
      - APPLICATION_MAIL_API_KEY=${MAIL_API_KEY}
      - APPLICATION_MAIL_API_URL=${MAIL_API_URL}
      - APPLICATION_MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - APPLICATION_MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - APPLICATION_MAIL_TEST_MODE=false
      - APPLICATION_MAIL_CONTACT_UPDATE_RECIPIENT=${CONTACT_UPDATE_RECIPIENT}
      - APPLICATION_ORCID_API_CLIENT_ID=${TOKEN_EXCHANGE_CLIENT_ID}
      - APPLICATION_ORCID_API_CLIENT_SECRET=${TOKEN_EXCHANGE_CLIENT_SECRET}
      - APPLICATION_SALESFORCE_CLIENT_ENDPOINT=${SALESFORCE_ENDPOINT}
      - APPLICATION_SALESFORCE_TOKEN_ENDPOINT=${TOKEN_EXCHANGE_ENDPOINT}
      - APPLICATION_REPORTS_MEMBER_DASHBOARD_URL=${HOLISTICS_MEMBER_DASHBOARD_URL}
      - APPLICATION_REPORTS_MEMBER_DASHBOARD_SECRET=${HOLISTICS_MEMBER_DASHBOARD_SECRET}
      - APPLICATION_REPORTS_INTEGRATION_DASHBOARD_URL=${HOLISTICS_INTEGRATION_DASHBOARD_URL}
      - APPLICATION_REPORTS_INTEGRATION_DASHBOARD_SECRET=${HOLISTICS_INTEGRATION_DASHBOARD_SECRET}
      - APPLICATION_REPORTS_CONSORTIA_DASHBOARD_URL=${HOLISTICS_CONSORTIA_DASHBOARD_URL}
      - APPLICATION_REPORTS_CONSORTIA_DASHBOARD_SECRET=${HOLISTICS_CONSORTIA_DASHBOARD_SECRET}
      - APPLICATION_REPORTS_AFFILIATION_DASHBOARD_URL=${HOLISTICS_AFFILIATION_DASHBOARD_URL}
      - APPLICATION_REPORTS_AFFILIATION_DASHBOARD_SECRET=${HOLISTICS_AFFILIATION_DASHBOARD_SECRET}
      - APPLICATION_REPORTS_CONSORTIA_MEMBER_AFFILIATION_DASHBOARD_URL=${HOLISTICS_MEMBERAFFILIATIONS_DASHBOARD_URL}
      - APPLICATION_REPORTS_CONSORTIA_MEMBER_AFFILIATION_DASHBOARD_SECRET=${HOLISTICS_MEMBERAFFILIATIONS_DASHBOARD_SECRET}
      - APPLICATION_SECURITY_ISSUER_URL=${ISSUER_URL}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs


  r7insight_docker:
    restart: unless-stopped
    image: rapid7/r7insight_docker:4.0.0
    security_opt:
      - no-new-privileges
    environment:
      - INSIGHT_TOKEN=${INSIGHT_TOKEN}
    command: -r us -j --no-stats --no-docker-events --skipByName '.*jhipster-registry.*'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ui-2:
    restart: unless-stopped
    image: ${DOCKER_REG}/ui-2:${TAG}
    build:
      context: ui-2
    environment:
      - APPLICATION_SECURITY_ISSUER_URL=${ISSUER_URL}
    volumes:
      - ${LOG_VOLUME:-/var/tmp/}:/logs
    ports:
      - 8091:8090




