name: Prettier & Lint
on:
  push:
    branches: [ main ]
    paths-ignore:
      # Ignore workflow changes
      - '.github/**'

  pull_request:
    branches: [ main ]

  workflow_call:
  workflow_dispatch:
jobs:
  format-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"
      - name: Install dependencies
        working-directory: ui
        run: npm ci
      - name: Run formatter
        working-directory: ui
        run: npm run format:cli

  format-ui-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "ui-2/package-lock.json"
      - name: Install dependencies
        working-directory: ui-2
        run: npm ci
      - name: Run formatter
        working-directory: ui-2
        run: npm run format:cli

