---
name: lint_private

# we don't pay for pre-commit-ci yet so need this for private repos

permissions:
  checks: write
  # allow pre-commit to write back to this repo
  contents: write
  issues: read
  pull-requests: write

"on":
  workflow_call:
  workflow_dispatch:
jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      # 1. Install mise and all tools defined in .mise.toml
      # This handles caching of the tools automatically.
      # v4
      - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0
        with:
          cache: true # Enabled by default
          # install: true (Default) runs 'mise install'

      - name: pre-commit
        uses: ORCID/pre-commit-bash-action@HEAD
        with:
          token: ${{ secrets.github_token }}
